"""Chat request and response schemas."""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Citizen conversation request."""
    query: str = Field(..., min_length=1, description="Citizen inquiry or statement")
    session_id: Optional[str] = Field(None, description="Optional conversation session ID")
    conversation_history: Optional[List[Dict[str, str]]] = Field(default_factory=list, description="Optional past turn history")


class ChatResponse(BaseModel):
    """Grounded citizen response generated by Agent Orchestrator."""
    answer: str = Field(description="Natural-language grounded answer")
    tools_called: List[str] = Field(default_factory=list, description="Tools invoked in this turn")
    sources: List[Dict[str, Any]] = Field(default_factory=list, description="Authoritative scheme excerpts retrieved")
    detected_needs: List[Dict[str, Any]] = Field(default_factory=list, description="Citizen needs identified")
    is_mock_used: bool = Field(default=False, description="Whether mock profile data was referenced")
    iterations: int = Field(default=0, description="Agent loop turns executed")
    quota_limited: bool = Field(default=False, description="True if LLM quota limit caused fallback")
    session_id: Optional[str] = Field(None, description="Active session ID")
