"""Controlled Need Taxonomy, lexicon patterns, and retrieval query mappings for Milestone 6."""
from typing import Dict, List, Set
from src.needs.models import NeedCategory


# Descriptions for each category in the controlled taxonomy
CATEGORY_DESCRIPTIONS: Dict[NeedCategory, str] = {
    NeedCategory.EMPLOYMENT: "Assistance with unemployment, job search, livelihood disruption, or wages.",
    NeedCategory.FINANCIAL_HARDSHIP: "Relief for acute poverty, low income, inability to pay bills, or debt.",
    NeedCategory.EDUCATION: "Support for schooling, tuition fees, college education, books, or scholarships.",
    NeedCategory.HOUSING: "Assistance with shelter, rent, affordable housing, or homelessness.",
    NeedCategory.HEALTHCARE: "Aid for medical treatment, hospital expenses, illness, or health coverage.",
    NeedCategory.AGRICULTURE: "Support for farmers, crop damage, agricultural inputs, or rural livelihoods.",
    NeedCategory.ENTREPRENEURSHIP: "Early-stage business creation, seed capital, incubation, or DPIIT recognition.",
    NeedCategory.SOCIAL_WELFARE: "General social safety net, welfare pensions, widow support, or social security.",
    NeedCategory.DISABILITY_SUPPORT: "Assistance for persons with disabilities (PwD), assistive aids, or pensions.",
    NeedCategory.SENIOR_CITIZEN_SUPPORT: "Welfare and pensions for elderly citizens and retirees without support.",
    NeedCategory.WOMEN_SUPPORT: "Empowerment, maternal assistance, girl child welfare, or self-help groups.",
    NeedCategory.SKILL_DEVELOPMENT: "Vocational training, technical trade courses, ITI, or apprenticeships.",
    NeedCategory.FOOD_BASIC_NEEDS: "Subsidized food grains, ration card support, or emergency food relief.",
    NeedCategory.OTHER: "Legitimate citizen welfare requirements outside the standard categories.",
    NeedCategory.UNKNOWN_AMBIGUOUS: "Unspecified or vague requests requiring further clarification.",
}


# Curated keyword/phrase patterns for deterministic offline matching (ordered by specificity)
LEXICON_PATTERNS: Dict[NeedCategory, List[str]] = {
    NeedCategory.EMPLOYMENT: [
        "lost my job",
        "lost job",
        "unemployed",
        "job loss",
        "looking for work",
        "looking for a job",
        "looking for job",
        "need a job",
        "need work",
        "find work",
        "laid off",
        "layoff",
        "fired",
        "no job",
        "out of work",
        "unemployment",
        "daily wage",
        "salary issue",
        "livelihood",
    ],
    NeedCategory.FINANCIAL_HARDSHIP: [
        "income is very low",
        "income is low",
        "low income",
        "cannot pay bills",
        "can't pay bills",
        "cannot pay monthly",
        "cannot pay my",
        "no savings",
        "no money",
        "financial crisis",
        "financial hardship",
        "financial struggle",
        "in debt",
        "debt burden",
        "extreme poverty",
        "poor financial",
        "cannot afford",
        "can't afford",
    ],
    NeedCategory.EDUCATION: [
        "children studying",
        "kids studying",
        "child studying",
        "school fees",
        "college fees",
        "school support",
        "education support",
        "education help",
        "pay school",
        "paying school fees",
        "tuition fees",
        "tuition fee",
        "scholarship",
        "college tuition",
        "books and uniform",
        "student loan",
        "student financial",
    ],
    NeedCategory.HOUSING: [
        "need housing",
        "housing help",
        "help with housing",
        "need a house",
        "affordable housing",
        "affordable house",
        "pucca home",
        "pucca house",
        "rent help",
        "help paying rent",
        "cannot pay rent",
        "can't pay rent",
        "homeless",
        "affordable shelter",
        "roof over our heads",
        "housing scheme",
        "housing support",
        "house grant",
        "home repair grant",
        "house",
        "housing",
    ],
    NeedCategory.HEALTHCARE: [
        "medical bills",
        "hospital bills",
        "medical treatment",
        "hospital treatment",
        "illness",
        "medicine costs",
        "hospital and medicine costs",
        "medical expenses",
        "health treatment",
        "surgery cost",
        "expensive medicine",
        "cancer treatment",
        "chronic illness",
        "hospital",
        "medicine",
        "medicines",
        "doctor",
        "medical",
    ],
    NeedCategory.AGRICULTURE: [
        "small farmer",
        "crop failure",
        "crop damage",
        "crop loss",
        "drought loss",
        "farming subsidy",
        "fertilizer subsidy",
        "seeds and fertilizer",
        "farmer support",
        "agricultural loan",
        "pm kisan",
        "tractor subsidy",
        "irrigation help",
        "smallholder farmer",
        "farmer",
        "farming",
        "agriculture",
    ],
    NeedCategory.ENTREPRENEURSHIP: [
        "start a business",
        "start business",
        "starting a business",
        "startup seed fund",
        "seed fund",
        "seed fund grant",
        "seed funding",
        "seed grant",
        "dpiit recognition",
        "dpiit recognized",
        "business incubation",
        "early-stage startup",
        "early stage startup",
        "innovative tech startup",
        "tech startup",
        "prototype grant",
        "startup capital",
        "startup",
        "entrepreneur",
    ],
    NeedCategory.DISABILITY_SUPPORT: [
        "disabled person",
        "disabled",
        "disability",
        "disability pension",
        "person with disability",
        "persons with disabilities",
        "pwd certificate",
        "assistive device",
        "wheelchair",
        "prosthetic",
        "visually impaired",
        "hearing impaired",
        "locomotor disability",
        "handicapped",
    ],
    NeedCategory.SENIOR_CITIZEN_SUPPORT: [
        "old age pension",
        "senior citizen",
        "elderly parent",
        "elderly mother",
        "elderly care",
        "retired without pension",
        "senior citizen welfare",
        "aged 65",
        "aged 70",
    ],
    NeedCategory.WOMEN_SUPPORT: [
        "maternity benefit",
        "maternity financial",
        "single mother",
        "widow pension",
        "girl child education",
        "women entrepreneur",
        "self help group",
        "mahila",
    ],
    NeedCategory.SKILL_DEVELOPMENT: [
        "skill training",
        "skills training",
        "vocational training",
        "skill development",
        "learn a trade",
        "technical training",
        "pmkvy",
        "iti training",
        "apprentice",
        "job training",
    ],
    NeedCategory.FOOD_BASIC_NEEDS: [
        "ration card",
        "food security",
        "subsidized food",
        "no food",
        "free ration",
        "grocery support",
        "food assistance",
    ],
    NeedCategory.SOCIAL_WELFARE: [
        "social security",
        "welfare pension",
        "welfare benefit",
        "government welfare",
    ],
}


# Internal semantic retrieval queries keyed by category
# NOTE: These are INTERNAL search strings optimized for M1 semantic search;
# they are NOT official government scheme names or eligibility statements.
SUGGESTED_SCHEME_QUERIES: Dict[NeedCategory, str] = {
    NeedCategory.EMPLOYMENT: "employment assistance livelihood job opportunities wage support",
    NeedCategory.FINANCIAL_HARDSHIP: "financial assistance monetary grant relief welfare support",
    NeedCategory.EDUCATION: "scholarship education financial assistance student school tuition fees",
    NeedCategory.HOUSING: "housing assistance affordable shelter home grant scheme",
    NeedCategory.HEALTHCARE: "healthcare medical treatment insurance hospital aid",
    NeedCategory.AGRICULTURE: "farmer agriculture crop loss subsidy input assistance",
    NeedCategory.ENTREPRENEURSHIP: "Startup India Seed Fund Scheme DPIIT early stage grant prototype commercialization",
    NeedCategory.SOCIAL_WELFARE: "social security welfare pension financial assistance",
    NeedCategory.DISABILITY_SUPPORT: "disability pension assistive aid support scheme PwD",
    NeedCategory.SENIOR_CITIZEN_SUPPORT: "senior citizen old age pension elderly welfare",
    NeedCategory.WOMEN_SUPPORT: "women empowerment maternal benefit girl child financial aid",
    NeedCategory.SKILL_DEVELOPMENT: "skill development vocational training certification apprenticeship",
    NeedCategory.FOOD_BASIC_NEEDS: "food security subsidized ration public distribution grains",
    NeedCategory.OTHER: "government financial assistance welfare scheme",
}


# General, ambiguous keywords that signal a request for help but lack specific domain context
# General, ambiguous keywords that signal a request for help but lack specific domain context
AMBIGUOUS_NEED_INDICATORS: Set[str] = {
    "help",
    "support",
    "assistance",
    "schemes",
    "benefits",
    "government scheme",
    "government help",
    "for my family",
    "need help",
    "need support",
    "what can i get",
    "what is available",
}


# Non-need conversational greetings and closings
CONVERSATIONAL_GREETINGS: Set[str] = {
    "hello",
    "hi",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "namaste",
    "how are you",
    "thank you",
    "thanks",
    "bye",
    "goodbye",
    "assistant",
    "ai",
    "bot",
    "there",
}
